2017-03-02 17:05:19,202 pypet ERROR    ERROR occurred during a single run! 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pypet/environment.py", line 260, in _sigint_handling_single_run
    return _single_run(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pypet/environment.py", line 315, in _single_run
    result = runfunc(traj, *runargs, **kwrunparams)
  File "/home/robin/Projects/ValidationTools/pet/Explore_params.py", line 45, in assembly_detection
    min_n_estimate = min(relevant_EVs)
TypeError: 'int' object is not iterable
